live_config_reload = true
working_directory = "None"
[shell]
program = "wsl -d Arch"
args = ["--cd ~"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xc9826b"
index = 16

[[colors.indexed_colors]]
color = "0xbf88bc"
index = 17

[colors.bright]
black = "0x465780"
blue = "0x8cafd2"
cyan = "0x93ccdc"
green = "0xb1d196"
magenta = "0xc895bf"
red = "0xd06f79"
white = "0xe7ecf4"
yellow = "0xf0d399"

[colors.normal]
black = "0x3b4252"
blue = "0x81a1c1"
cyan = "0x88c0d0"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8b"

[colors.primary]
background = "0x2e3440"
foreground = "0xcdcecf"

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
LC_ALL = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 11.5
normal = { family = "SauceCodePro Nerd Font", style = "Regular"}
bold = { family = "SauceCodePro Nerd Font", style = "Bold"}
italic = { family = "SauceCodePro Nerd Font", style = "Italic"}

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"


[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"


[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"


[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"



[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Control"


[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"


[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.93
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 1
