
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[env]
TERM = "xterm-256color"
LC_ALL = "en_US.UTF-8"

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false


[font]
size = 14.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
offset = { x = 0, y = 0 }


[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
binding = { key = "O", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
persist = false
post_processing = true


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"


[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"


[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Super"


[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002c"
key = "N"
mods = "Control|Shift"



[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Control"


[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"


[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`| =\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"
dimensions = { columns = 80, lines = 24 }
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }
class = "Alacritty"

