
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

[colors.normal]
black = '0x090618'
red = '0xc34043'
green = '0x76946a'
yellow = '0xc0a36e'
blue = '0x7e9cd8'
magenta = '0x957fb8'
cyan = '0x6a9589'
white = '0xc8c093'

[colors.bright]
black = '0x727169'
red = '0xe82424'
green = '0x98bb6c'
yellow = '0xe6c384'
blue = '0x7fb4ca'
magenta ='0x938aa9'
cyan = '0x7aa89f'
white = '0xdcd7ba'

[colors.selection]
background = '0x2d4f67'
foreground = '0xc8c093'

[[colors.indexed_colors]]
index = 16
color = '0xffa066'
[[colors.indexed_colors]]
index = 17
color = '0xff5d62'

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
LC_ALL = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 13
normal = { family = "Jetbrains Mono Nerd Font", style = "Regular"}
bold = { family = "Jetbrains Mono Nerd Font", style = "Bold"}
italic = { family = "Jetbrains Mono Nerd Font", style = "Italic"}

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"


[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"


[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"


[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002c"
key = "N"
mods = "Control|Shift"



[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Control"


[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"


[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.7
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 1

[general]
live_config_reload = true
working_directory = "None"
